Script updates

diff --git a/networks/upg/post-upg b/networks/upg/post-upg
--- a/networks/upg/post-upg
+++ b/networks/upg/post-upg
@@ -10,4 +10,9 @@ $EMD version # UPG_PLAN
 
 $EMD q authority gas-prices --home=.emd --node tcp://localhost:26657 --chain-id test
 
-$EMD query upgrade applied $UPG_PLAN
+if "$EMD" version 2>&1 > /dev/null | grep -q "$UPG_PLAN"; then
+    echo 'the chain upgrade succeeded!'
+else
+    echo 'the chain upgrade failed!'
+    exit 1;
+fi
diff --git a/networks/upg/post-upg-44 b/networks/upg/post-upg-44
--- a/networks/upg/post-upg-44
+++ b/networks/upg/post-upg-44
@@ -1,11 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 # Run post the upgrade to confirm upgraded values
 set -e
 
 EMD=.emd/cosmovisor/current/bin/emd
 
-UPG_PLAN=v44-upg-test
+UPG_PLAN="44-upg-test"
 
-$EMD version # UPG_PLAN
-
-$EMD query upgrade applied $UPG_PLAN
+if "$EMD" version 2>&1 > /dev/null | grep -q "$UPG_PLAN"; then
+    echo 'the v42 to v44 chain upgrade succeeded!'
+else
+    echo 'the chain upgrade failed!'
+    exit 1;
+fi
